### ISSUE TITLE
Improvement Project Structure

### ISSUE THREAD

**Issue by 1chooo** [IzYoBoiJay/ASCII-Space-Shooter#2]
### Descriptions
Hi! @IzYoBoiJay, During my previous work on a project related to `ncurses.h`, I also discovered a more effective project management approach. This approach involves two primary organizational methods:

- src directory: Within this directory, each class has a corresponding CPP file. This separation allows us to keep the class definitions and their implementation code separate, making the code more structured and readable.
- include directory: In this directory, all header files are stored. These header files contain the declarations of classes and prototypes of functions, enabling other code to reference and use these classes and functions.
By adopting this organizational structure, we can manage the project more efficiently and enhance the maintainability and reusability of the code.

I have taken the initiative to clone this project without obtaining your explicit permission. However, I would like to present the results to you before proceeding further. If you agree, I will initiate a pull request and submit it for your review. Additionally, I welcome any suggestions or feedback you may have, so please don't hesitate to send me a direct message.

### Demo
https://github.com/IzYoBoiJay/ASCII-Space-Shooter/assets/94162591/b749eafe-112f-47b8-a955-4b3ddd628c4e

BR, 
@1chooo

**Comment by IzYoBoiJay** [comment]
Hi @1chooo, I very much like this directory approach. It is very similar to my newer web application projects. Feel free to make a pull request for review. I am glad it helped your project, but if it doesn't hurt I'd simply like a mention of credit.

Cheers!

**Comment by 1chooo** [comment]
Hi! @IzYoBoiJay, Of course! My project is still ongoing, and I will definitely acknowledge your significant contribution to the project. However, as the semester has just ended and I have an upcoming summer internship, I am currently busy with my commitments. I will continue working on the project and once it is completed, I will notify you immediately. We can then discuss how to properly credit your invaluable assistance.

BR,
@1chooo
